spring:
  config:
    activate:
      on-profiles: test

aws:
  s3:
    bucket: stchatbotimagebucket
  stack.auto: false
  region.static: ap-northeast-2
  credentials:
    access-key: ${aws.access.key.id}
    secret-key: ${aws.secret.access.key}